export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const INIT_TIMEOUT = "INIT_TIMEOUT";
export const START_LOGOUT = "START_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";

export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";

export const ACTION_CART_START = "ACTION_CART_START";
export const FETCH_CART_START = "FETCH_CART_START";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS";

export const MODAL_CLOSE = "MODAL_CLOSE";
export const MODAL_OPEN = "MODAL_OPEN";
